### ISSUE TITLE
Error occured when run script "npm i" in example of "create-react-app"❌

### ISSUE THREAD

**Issue by cainull** [nvh95/jest-preview#147] opened 2022-06-16 14:40 UTC
**Describe the bug**
Error occured when run script "npm i" in example of "create-react-app"❌

**To Reproduce**
just CD into "examples\create-react-app" and run "npm i"┭┮﹏┭┮

**Expected behavior**
packages installed smoothly, then I can run the example.😄

**Screenshots**
![image](https://user-images.githubusercontent.com/45328460/174094568-da2fde9c-4e20-4ee1-8534-bb683666462a.png)

**Environment (please complete the following information)**

- OS: Windows 11
- Browser: chrome

**Additional context**
other examples may exist this problem(〃＞目＜)

**Comment by nvh95** [comment] 2022-06-17 05:34
@cainull Oh man, likely this issue is related to your folder name containing non-ASCII characters. Let me try to reproduce it.
In the meantime, you can work around by running:
```bash
npm install --ignore-scripts
# or
yarn install --ignore-scripts
```

**Comment by cainull** [comment] 2022-06-17 05:57
Thanks for replied! I'm careless🤭, I try to move the project to other folder with full ASCII path, then it works.
but if containing non-ASCII characters, error still occured when I run `npm install --ignore-scripts` .
so, **the temporary solution** is clone the project to the full-ASCII characters path, then **yarn intsall**

**Comment by nvh95** [comment] 2022-06-17 06:01
@cainull Oh, interesting. It’s definitely an issue with Jest Preview. I will try to reproduce on a Windows (unluckily I don’t have one with me right now). I tried on macOS but it works fine.
Can you copy the full path name? I will try with yours.
Please keep this issue open. After fixing it, can you help to verify it?

Thank you very much.

**Comment by cainull** [comment] 2022-06-17 06:04
it works when I run scripts npm install in the root path(./jest-preview), but when I cd into `exmaples/create-react-app` then run this scripts, it still won't work.

**Comment by cainull** [comment] 2022-06-17 06:06
![image](https://user-images.githubusercontent.com/45328460/174235605-af315d8f-1320-4d18-a745-9fc2c5b12f78.png)

**Comment by cainull** [comment] 2022-06-17 06:06
![image](https://user-images.githubusercontent.com/45328460/174235668-26490a68-3c63-4f0e-be2b-17c41a2106be.png)

**Comment by cainull** [comment] 2022-06-17 06:08
Oh, it's my present! I will verify it if bug fixed. 😄

**Comment by nvh95** [comment] 2022-06-17 09:41
Hi @cainull. Can you try to verify if the issue is resolved after running:

```bash
npm install jest-preview@0.2.5-alpha.1 --save-dev
# or
yarn add jest-preview@0.2.5-alpha.1 -D
```

Thanks.

**Comment by cainull** [comment] 2022-06-17 09:45
OK. I'll do it right now. 👍

**Comment by nvh95** [comment] 2022-06-18 02:24
Thank you @cainull. Please let us know if the issue has been resolved.

**Comment by cainull** [comment] 2022-06-18 02:44
yeah. This problem has been solved😄.

**Comment by cainull** [comment] 2022-06-18 02:46
but I'm curious about its reason

**Comment by nvh95** [comment] 2022-06-18 08:25
@cainull Thank you very much for your confirmation.

The issue is this line of code

```
// pacakge.json
"postinstall": "bash -c \"[[ '$INIT_CWD' == '$PWD' ]] && echo Inside Jest Preview. Do not clear Cache. || jest --clearCache || echo\"",
```

Since in some cases, we need to clear the Jest cache to avoid  CSS and images getting cached by the old code transformers. So we have a `postinstall` script to automatically clear Jest cache after installing `jest-preview`. The script is written in bash. However, this script is not stable in some circumstances (e.g: folder name is non-ASCII on windows).

I resolve it by moving this logic into a separate javascript file. You can read more in this commit https://github.com/nvh95/jest-preview/commit/7cf6c22971fd051eeac2d2b3c3fe28c0ac18f3fc#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R52

**Comment by nvh95** [comment] 2022-06-19 17:09
@cainull I'm closing this issue since it has been resolved. Feel free to keep discussing more if you want to know anything else.

**Comment by nvh95** [comment] 2022-06-19 17:09
@all-contributors please add @cainull for bug

**Closed by nvh95** 2022-06-19 17:09 UTC
Labels: bug, operating system

**Comment by cainull** [comment] 2022-06-20 01:58
Thanks for explanation! I would keep focus on this project. 😄

**Comment by nvh95** [comment] 2022-06-20 02:00
@cainull Thank you. Share me your project if you integrate `jest-preview`. Let me know if you have any issues when doing it.
